#!/usr/bin/env bash
# Displays the numbers 1 to 100
#	Displays "FizzBuzz" when number is a multipe of both 3 and 5
#	Displays "Fizz" when number is a multiple of 3
#	Displays "Buzz" when number is a multiple of 5

for num in {1..100}
do
	if (( num % 3 == 0 && num % 5 == 0 ))
	then
		echo "FizzBuzz"
	elif (( num % 3 == 0 ))
	then
		echo "Fizz"
	elif (( num % 5 == 0 ))
	then
		echo "Buzz"
	else
		echo "$num"
	fi
done
