#!/usr/bin/env bash
# Displays the contents of the /etc/passwd file
# Only displays username, user id and user's home directory path

while read -r passwd; do
	echo "$passwd" | cut -d ':' -f 1,3,6
done < "/etc/passwd"
