#!/usr/bin/env bash

# Parses apache log files in list format
#	Groups visitoes by IP and HTTP ststus codes
#	Displays the number of occurrences, IP, HTTP status
#+	code of each log, in sorted order

awk '{ print $1 " " $9}' apache-access.log | sort | uniq -c | sort -rn
