#!/usr/bin/env bash
# Loops from 1 to 10 and displays:
#	"bad luck" for the 4th iteration
#	"good luck" for the 8th iteration
#	"Best School" for the other iterations

index=1

while [ $index -le 10 ]
do
	if [ $index -eq 4 ]
	then
		echo "bad luck"
	elif [ $index -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((index++))
done
